/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fs_server.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

int
_mi_get_size_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (mi_get_size_1_svc(*argp, result, rqstp));
}

int
_mi_creat_1 (mi_creat_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (mi_creat_1_svc(argp->name, argp->modo, result, rqstp));
}

int
_mi_open_1 (mi_open_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (mi_open_1_svc(argp->name, argp->flags, result, rqstp));
}

int
_mi_close_1 (int  *argp, void *result, struct svc_req *rqstp)
{
	return (mi_close_1_svc(*argp, result, rqstp));
}

int
_mi_unlink_1 (char * *argp, void *result, struct svc_req *rqstp)
{
	return (mi_unlink_1_svc(*argp, result, rqstp));
}

int
_mi_read_1 (mi_read_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (mi_read_1_svc(argp->fd, argp->pos, argp->size, result, rqstp));
}

int
_mi_write_1 (mi_write_1_argument *argp, void *result, struct svc_req *rqstp)
{
	return (mi_write_1_svc(argp->fd, argp->data, argp->pos, argp->size, result, rqstp));
}

static void
fs_server_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		int mi_get_size_1_arg;
		mi_creat_1_argument mi_creat_1_arg;
		mi_open_1_argument mi_open_1_arg;
		int mi_close_1_arg;
		char *mi_unlink_1_arg;
		mi_read_1_argument mi_read_1_arg;
		mi_write_1_argument mi_write_1_arg;
	} argument;
	union {
		int mi_get_size_1_res;
		int mi_creat_1_res;
		int mi_open_1_res;
		int mi_close_1_res;
		int mi_unlink_1_res;
		ReadRes mi_read_1_res;
		int mi_write_1_res;
	} result;
	bool_t retval;
	xdrproc_t _xdr_argument, _xdr_result;
	bool_t (*local)(char *, void *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case mi_get_size:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_get_size_1;
		break;

	case mi_creat:
		_xdr_argument = (xdrproc_t) xdr_mi_creat_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_creat_1;
		break;

	case mi_open:
		_xdr_argument = (xdrproc_t) xdr_mi_open_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_open_1;
		break;

	case mi_close:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_close_1;
		break;

	case mi_unlink:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_unlink_1;
		break;

	case mi_read:
		_xdr_argument = (xdrproc_t) xdr_mi_read_1_argument;
		_xdr_result = (xdrproc_t) xdr_ReadRes;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_read_1;
		break;

	case mi_write:
		_xdr_argument = (xdrproc_t) xdr_mi_write_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (bool_t (*) (char *, void *,  struct svc_req *))_mi_write_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	retval = (bool_t) (*local)((char *)&argument, (void *)&result, rqstp);
	if (retval > 0 && !svc_sendreply(transp, (xdrproc_t) _xdr_result, (char *)&result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	if (!fs_server_1_freeresult (transp, _xdr_result, (caddr_t) &result))
		fprintf (stderr, "%s", "unable to free results");

	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (FS_SERVER, FS_SERVER_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, FS_SERVER, FS_SERVER_V1, fs_server_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (FS_SERVER, FS_SERVER_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, FS_SERVER, FS_SERVER_V1, fs_server_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (FS_SERVER, FS_SERVER_V1, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
