/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */	

#include "fs_server.h"

void
fs_server_1(char *host, char* remotefile, char* localfile)
{
	CLIENT *clnt;

	enum clnt_stat retval_1;
	int result_create;

	enum clnt_stat retval_3;
	int result_open;
	
	enum clnt_stat retval_4;
	int result_close;
	
	enum clnt_stat retval_6;
	int result_write;
	RWData result_read;


#ifndef	DEBUG
	clnt = clnt_create (host, FS_SERVER, FS_SERVER_V1, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	retval_1 = mi_creat_1(remotefile, O_CREAT, &result_create,  clnt);
	if (retval_1 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	retval_3 = mi_open_1(remotefile, WRITEMODE, &result_open, clnt);
	if (retval_3 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}

	int localfd = open(localfile, O_RDONLY | O_CREAT, 0666);
	if (localfd < 0){
		printf("Error opening local file \n");
	}
	
	int result_getSize = lseek(localfd, 0, SEEK_END);
	if (result_getSize < 0){
		printf("Error seeking local file \n");
	}
	
	int it = result_getSize/NFSMAXDATA2;
	int realsize;
	int chuck;
	int atleast = 0;
	int position = 0;
    int pointer = 0;

	while(it >= 0){
		if(it==0){
			realsize = result_getSize - ((result_getSize/NFSMAXDATA2)*NFSMAXDATA2);
			if(atleast==1){
                result_read.RWData_val = (char *) realloc(result_read.RWData_val,realsize);
            }else{
                result_read.RWData_val = malloc(realsize);
            }

		}else{
			if(it == result_getSize/NFSMAXDATA2){
				realsize=NFSMAXDATA2;
                result_read.RWData_val = malloc(realsize);
			}
		}

		memset(result_read.RWData_val, 0, realsize);
		result_read.RWData_len=realsize;
		position = pointer*NFSMAXDATA2;

		lseek(localfd, position, 0);
		
		chuck = read(localfd, result_read.RWData_val, realsize);
		if (chuck < 0){
			printf("Error reading local file \n");
		}
		
		retval_6 = mi_write_1(result_open, result_read, position, realsize, &result_write, clnt);
		if (retval_6 != RPC_SUCCESS) {
			clnt_perror (clnt, "call failed");
		}
		
		it--;
        pointer++;
		atleast = 1;
	}	
	

	retval_4 = mi_close_1(result_open, &result_close, clnt);
	if (retval_4 != RPC_SUCCESS) {
		clnt_perror (clnt, "call failed");
	}
	
	chuck = close(localfd);
	if (chuck < 0){
		printf("Error closing local file \n");
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

int
main (int argc, char *argv[])
{
	char *host;
	char *remote;
	char *local;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

	host = argv[2];
	remote = argv[3];
	local = argv[1];
	fs_server_1 (host, remote, local);
	exit (0);
}
